name: Deploy site via Fleek
on: push
jobs:
  deploy-to-fleek:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Fleek CLI
        run: npm i -g @fleekxyz/cli
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            override: true
      - name: Run cargo bench
        uses: actions-rs/cargo@v1
        with:
          command: bench
      - name: Build & deploy sites
        run: fleek sites deploy
